/**
 * @packageDocumentation
 * Sidebar structure for the primary documentation section under `docs/`.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        {
            id: "intro",
            label: "Overview",
            type: "doc",
        },
        {
            id: "getting-started",
            label: "Getting Started",
            type: "doc",
        },
        {
            type: "html",
            defaultStyle: true,
            value: '<span class="menu__section-title">Reference</span>',
        },
        {
            href: "/docs/rules/overview",
            label: "Rules Overview",
            type: "link",
        },
        {
            href: "/docs/rules/getting-started",
            label: "Rules Getting Started",
            type: "link",
        },
        {
            href: "/docs/rules/presets",
            label: "Presets",
            type: "link",
        },
        {
            label: "Shipped Rules",
            type: "category",
            collapsible: true,
            collapsed: false,
            items: [
                {
                    href: "/docs/rules/write-good-comments",
                    label: "R001 write-good-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/task-comment-format",
                    label: "R002 task-comment-format",
                    type: "link",
                },
                {
                    href: "/docs/rules/inclusive-language-comments",
                    label: "R003 inclusive-language-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/no-profane-comments",
                    label: "R004 no-profane-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/spellcheck-comments",
                    label: "R005 spellcheck-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/readability-comments",
                    label: "R006 readability-comments",
                    type: "link",
                },
            ],
        },
        {
            label: "Developer",
            type: "category",
            collapsible: true,
            collapsed: false,
            link: {
                id: "developer/index",
                type: "doc",
            },
            items: [
                "developer/index",
                {
                    label: "API Reference",
                    type: "category",
                    collapsible: true,
                    collapsed: false,
                    link: {
                        id: "developer/api/README",
                        type: "doc",
                    },
                    items: [
                        {
                            dirName: "developer/api",
                            type: "autogenerated",
                        },
                    ],
                },
            ],
        },
    ],
};

export default sidebars;
