/**
 * @packageDocumentation
 * Sidebar structure for the primary documentation section under `docs/`.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
    docs: [
        {
            id: "intro",
            label: "📖 Overview",
            type: "doc",
        },
        {
            id: "getting-started",
            label: "💨 Getting Started",
            type: "doc",
        },
        {
            defaultStyle: true,
            type: "html",
            value: '<span class="menu__section-title">Reference</span>',
        },
        {
            href: "/docs/rules/overview",
            label: "📏 Rules Overview",
            type: "link",
        },
        {
            href: "/docs/rules/getting-started",
            label: "🧑‍💻 Rules Getting Started",
            type: "link",
        },
        {
            href: "/docs/rules/presets",
            label: "🎛️ Presets",
            type: "link",
        },
        {
            collapsed: false,
            collapsible: true,
            items: [
                {
                    href: "/docs/rules/write-good-comments",
                    label: "R001 ✍️ write-good-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/task-comment-format",
                    label: "R002 📝 task-comment-format",
                    type: "link",
                },
                {
                    href: "/docs/rules/inclusive-language-comments",
                    label: "R003 🌐 inclusive-language-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/no-profane-comments",
                    label: "R004 🚫 no-profane-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/spellcheck-comments",
                    label: "R005 🔤 spellcheck-comments",
                    type: "link",
                },
                {
                    href: "/docs/rules/readability-comments",
                    label: "R006 👓 readability-comments",
                    type: "link",
                },
            ],
            label: "Shipped Rules",
            type: "category",
        },
        {
            collapsed: false,
            collapsible: true,
            items: [
                "developer/index",
                {
                    collapsed: false,
                    collapsible: true,
                    items: [
                        {
                            dirName: "developer/api",
                            type: "autogenerated",
                        },
                    ],
                    label: "🛠️ API Reference",
                    link: {
                        id: "developer/api/index",
                        type: "doc",
                    },
                    type: "category",
                },
            ],
            label: "Developer",
            link: {
                id: "developer/index",
                type: "doc",
            },
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
