declare const styles: {
    readonly markdown: string;
    readonly menu__link: string;
    readonly "menu__list-item--collapsed": string;
    readonly "menu__list-item-collapsible": string;
    readonly "sb-cat-api-runtime": string;
    readonly "sb-cat-api-types": string;
    readonly "sb-cat-developer": string;
    readonly "sb-cat-developer-adr": string;
    readonly "sb-cat-presets": string;
    readonly "sb-cat-rules": string;
    readonly "sb-cat-rules-ts-extras": string;
    readonly "sb-cat-rules-type-fest": string;
    readonly "sb-doc-api-overview": string;
    readonly "sb-doc-getting-started": string;
    readonly "sb-doc-overview": string;
    readonly "theme-doc-sidebar-item-link-level-1": string;
    readonly "theme-doc-sidebar-item-link-level-2": string;
    readonly "theme-doc-sidebar-item-link-level-3": string;
    readonly "theme-doc-sidebar-menu": string;
};
export = styles;
